"""phase6 accounting collections

Revision ID: 3ed73c662ea6
Revises: 5a928d548451
Create Date: 2026-07-11 13:14:10.324218
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3ed73c662ea6"
down_revision: str | None = "5a928d548451"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "type",
            sa.Enum("ASSET", "LIABILITY", "INCOME", "EXPENSE", "EQUITY", name="account_type"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_accounts_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
        sa.UniqueConstraint("organization_id", "code", name="uq_account_code"),
    )
    op.create_index(
        op.f("ix_accounts_organization_id"), "accounts", ["organization_id"], unique=False
    )
    op.create_table(
        "journal_entries",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=True),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("narration", sa.String(length=300), nullable=True),
        sa.Column("source_document_type", sa.String(length=50), nullable=True),
        sa.Column("source_document_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=op.f("fk_journal_entries_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_journal_entries_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_journal_entries_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journal_entries")),
    )
    op.create_index(
        op.f("ix_journal_entries_organization_id"),
        "journal_entries",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "journal_entry_lines",
        sa.Column("journal_entry_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("debit", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("credit", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(debit = 0) <> (credit = 0)",
            name=op.f("ck_journal_entry_lines_ck_jline_one_side_only"),
        ),
        sa.CheckConstraint(
            "debit >= 0 AND credit >= 0", name=op.f("ck_journal_entry_lines_ck_jline_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_journal_entry_lines_account_id_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"],
            ["journal_entries.id"],
            name=op.f("fk_journal_entry_lines_journal_entry_id_journal_entries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journal_entry_lines")),
    )
    op.create_index(
        op.f("ix_journal_entry_lines_account_id"),
        "journal_entry_lines",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_journal_entry_lines_journal_entry_id"),
        "journal_entry_lines",
        ["journal_entry_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_journal_entry_lines_journal_entry_id"), table_name="journal_entry_lines")
    op.drop_index(op.f("ix_journal_entry_lines_account_id"), table_name="journal_entry_lines")
    op.drop_table("journal_entry_lines")
    op.drop_index(op.f("ix_journal_entries_organization_id"), table_name="journal_entries")
    op.drop_table("journal_entries")
    op.drop_index(op.f("ix_accounts_organization_id"), table_name="accounts")
    op.drop_table("accounts")
    # ### end Alembic commands ###
