"""phase5 wholesale sales orders

Revision ID: 5a928d548451
Revises: d183ffc72cb1
Create Date: 2026-07-11 13:07:21.870375
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5a928d548451"
down_revision: str | None = "d183ffc72cb1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sales_orders",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=True),
        sa.Column("warehouse_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("salesperson_id", sa.UUID(), nullable=True),
        sa.Column("order_number", sa.String(length=40), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUOTATION",
                "CONFIRMED",
                "PARTIALLY_DISPATCHED",
                "DISPATCHED",
                "INVOICED",
                "CANCELLED",
                name="sales_order_status",
            ),
            nullable=False,
        ),
        sa.Column("order_date", sa.Date(), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("tax_total", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("grand_total", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("credit_override_approved", sa.Boolean(), nullable=False),
        sa.Column("sales_invoice_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=op.f("fk_sales_orders_branch_id_branches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_sales_orders_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_sales_orders_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sales_invoice_id"],
            ["sales_invoices.id"],
            name=op.f("fk_sales_orders_sales_invoice_id_sales_invoices"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["salesperson_id"],
            ["users.id"],
            name=op.f("fk_sales_orders_salesperson_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_sales_orders_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_orders")),
        sa.UniqueConstraint("organization_id", "order_number", name="uq_sales_order_no"),
    )
    op.create_index(
        op.f("ix_sales_orders_customer_id"), "sales_orders", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_sales_orders_organization_id"), "sales_orders", ["organization_id"], unique=False
    )
    op.create_table(
        "sales_order_items",
        sa.Column("sales_order_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("base_quantity", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("reserved_quantity", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("dispatched_quantity", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("price_source", sa.String(length=30), nullable=False),
        sa.Column("discount_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("taxable_value", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("gst_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_sales_order_items_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sales_order_id"],
            ["sales_orders.id"],
            name=op.f("fk_sales_order_items_sales_order_id_sales_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_order_items")),
    )
    op.create_index(
        op.f("ix_sales_order_items_sales_order_id"),
        "sales_order_items",
        ["sales_order_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sales_order_items_sales_order_id"), table_name="sales_order_items")
    op.drop_table("sales_order_items")
    op.drop_index(op.f("ix_sales_orders_organization_id"), table_name="sales_orders")
    op.drop_index(op.f("ix_sales_orders_customer_id"), table_name="sales_orders")
    op.drop_table("sales_orders")
    # ### end Alembic commands ###
